# Generated by Django 3.2 on 2021-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='state',
            field=models.CharField(default='1', max_length=1),
            preserve_default=False,
        ),
    ]
