# Generated by Django 3.2.3 on 2021-06-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daemon', '0002_pages_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deltd_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('path', models.TextField()),
                ('title', models.TextField()),
                ('subj', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('pub_time', models.DateTimeField(verbose_name='time_published')),
                ('mk_array', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mdfyd_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('path', models.TextField()),
                ('title', models.TextField()),
                ('subj', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('pub_time', models.DateTimeField(verbose_name='time_published')),
                ('mk_array', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PageInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('path', models.TextField()),
                ('title', models.TextField()),
                ('subj', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('pub_time', models.DateTimeField(verbose_name='time_published')),
                ('mk_array', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='pages',
            name='aprnc',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='mk_array',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='path',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='pub_time',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='subj',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='typ',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='views',
        ),
    ]
